-- Spring Batch Meta Tables for PostgreSQL
-- Job 的基本資料（名稱、參數)
CREATE TABLE IF NOT EXISTS BATCH_JOB_INSTANCE (
    JOB_INSTANCE_ID BIGINT NOT NULL PRIMARY KEY,
    VERSION         BIGINT,
    JOB_NAME        VARCHAR(100) NOT NULL,
    JOB_KEY         VARCHAR(32)  NOT NULL,
    CONSTRAINT JOB_INST_UN UNIQUE (JOB_NAME, JOB_KEY)
);

-- Job 每次執行的狀態（成功 / 失敗 / 執行中）
CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION (
    JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    VERSION          BIGINT,
    JOB_INSTANCE_ID  BIGINT NOT NULL,
    CREATE_TIME      TIMESTAMP    NOT NULL,
    START_TIME       TIMESTAMP DEFAULT NULL,
    END_TIME         TIMESTAMP DEFAULT NULL,
    STATUS           VARCHAR(10),
    EXIT_CODE        VARCHAR(2500),
    EXIT_MESSAGE     VARCHAR(2500),
    LAST_UPDATED     TIMESTAMP,
    CONSTRAINT JOB_INST_EXEC_FK FOREIGN KEY (JOB_INSTANCE_ID) REFERENCES
    BATCH_JOB_INSTANCE (JOB_INSTANCE_ID)
);

-- Job 執行時帶的參數
CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION_PARAMS (
    JOB_EXECUTION_ID BIGINT       NOT NULL,
    PARAMETER_NAME   VARCHAR(100) NOT NULL,
    PARAMETER_TYPE   VARCHAR(100) NOT NULL,
    PARAMETER_VALUE  VARCHAR(2500),
    IDENTIFYING      CHAR(1)      NOT NULL,
    CONSTRAINT JOB_EXEC_PARAMS_FK FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES
    BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);

-- 每個 Step 的狀態與統計（讀幾筆、寫幾筆）
CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION (
    STEP_EXECUTION_ID  BIGINT       NOT NULL PRIMARY KEY,
    VERSION            BIGINT       NOT NULL,
    STEP_NAME          VARCHAR(100) NOT NULL,
    JOB_EXECUTION_ID   BIGINT       NOT NULL,
    CREATE_TIME        TIMESTAMP    NOT NULL,
    START_TIME         TIMESTAMP DEFAULT NULL,
    END_TIME           TIMESTAMP DEFAULT NULL,
    STATUS             VARCHAR(10),
    COMMIT_COUNT       BIGINT,
    READ_COUNT         BIGINT,
    FILTER_COUNT       BIGINT,
    WRITE_COUNT        BIGINT,
    READ_SKIP_COUNT    BIGINT,
    WRITE_SKIP_COUNT   BIGINT,
    PROCESS_SKIP_COUNT BIGINT,
    ROLLBACK_COUNT     BIGINT,
    EXIT_CODE          VARCHAR(2500),
    EXIT_MESSAGE       VARCHAR(2500),
    LAST_UPDATED       TIMESTAMP,
    CONSTRAINT JOB_EXEC_STEP_FK FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES
    BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);

-- Step 中斷時的快照（用於 Restart）
CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION_CONTEXT (
    STEP_EXECUTION_ID  BIGINT        NOT NULL PRIMARY KEY,
    SHORT_CONTEXT      VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT,
    CONSTRAINT STEP_EXEC_CTX_FK FOREIGN KEY (STEP_EXECUTION_ID) REFERENCES
    BATCH_STEP_EXECUTION (STEP_EXECUTION_ID)
);

-- Job 層級的中斷快照
CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION_CONTEXT (
    JOB_EXECUTION_ID   BIGINT        NOT NULL PRIMARY KEY,
    SHORT_CONTEXT      VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT,
    CONSTRAINT JOB_EXEC_CTX_FK FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES
    BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);

CREATE SEQUENCE IF NOT EXISTS BATCH_STEP_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS BATCH_JOB_EXECUTION_SEQ  MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS BATCH_JOB_SEQ            MAXVALUE 9223372036854775807 NO CYCLE;

-- OHLCV 歷史 K 線（統計套利軌核心數據）
CREATE TABLE IF NOT EXISTS ohlcv (
    id          BIGSERIAL PRIMARY KEY,
    symbol      VARCHAR(20)    NOT NULL,
    open_time   BIGINT         NOT NULL,
    open        DECIMAL(20, 8) NOT NULL,
    high        DECIMAL(20, 8) NOT NULL,
    low         DECIMAL(20, 8) NOT NULL,
    close       DECIMAL(20, 8) NOT NULL,
    volume      DECIMAL(20, 8) NOT NULL,
    interval    VARCHAR(10)    NOT NULL,
    created_at  TIMESTAMP DEFAULT NOW(),
    UNIQUE (symbol, open_time, interval)
);

-- 回測績效結果（每次回測 Job 的彙總）
CREATE TABLE IF NOT EXISTS backtest_result (
    id              BIGSERIAL PRIMARY KEY,
    job_id          VARCHAR(50)    NOT NULL UNIQUE,
    strategy        VARCHAR(50)    NOT NULL,
    symbol_a        VARCHAR(20)    NOT NULL,
    symbol_b        VARCHAR(20)    NOT NULL,
    start_date      DATE           NOT NULL,
    end_date        DATE           NOT NULL,
    sharpe_ratio    DECIMAL(10, 4),
    max_drawdown    DECIMAL(10, 4),
    win_rate        DECIMAL(10, 4),
    annual_return   DECIMAL(10, 4),
    total_trades    INT,
    created_at      TIMESTAMP DEFAULT NOW()
);

-- 鏈上指標時序（鏈上信號軌核心數據）
CREATE TABLE IF NOT EXISTS on_chain_metrics (
    id                  BIGSERIAL PRIMARY KEY,
    recorded_at         TIMESTAMP      NOT NULL,
    fear_greed_index    INT,
    fear_greed_label    VARCHAR(20),
    btc_exchange_flow   DECIMAL(20, 2),
    nupl                DECIMAL(10, 4),
    sopr                DECIMAL(10, 4),
    created_at          TIMESTAMP DEFAULT NOW(),
    UNIQUE (recorded_at)
);
